/*
 * Rock Paper Scissors
 * This is a practice with swagger
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ggmartin.paperrockscissors.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * HandTypeDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-08T15:29:51.278Z")



public class HandTypeDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("desc")
  private String desc = null;

  public HandTypeDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Id of the game
   * @return id
  **/
  @ApiModelProperty(value = "Id of the game")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public HandTypeDTO desc(String desc) {
    this.desc = desc;
    return this;
  }

   /**
   * Id of the game
   * @return desc
  **/
  @ApiModelProperty(value = "Id of the game")
  public String getDesc() {
    return desc;
  }

  public void setDesc(String desc) {
    this.desc = desc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HandTypeDTO handTypeDTO = (HandTypeDTO) o;
    return Objects.equals(this.id, handTypeDTO.id) &&
        Objects.equals(this.desc, handTypeDTO.desc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, desc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HandTypeDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

